version: '3.8'

services:
  mineru-m1:
    build:
      context: .
      dockerfile: Dockerfile
      platform: linux/arm64  # M1芯片架构
    container_name: mineru-m1-api
    restart: unless-stopped
    ports:
      - "8000:8000"  # API端口
    environment:
      - MINERU_MODEL_SOURCE=huggingface
      - PYTHONPATH=/app
      - TORCH_NUM_THREADS=4  # 限制CPU线程数
      - OMP_NUM_THREADS=4
      - MKL_NUM_THREADS=4
    volumes:
      - mineru_models:/opt/models  # 模型持久化存储
      - mineru_cache:/root/.cache   # 缓存持久化
      - ./output:/app/output        # 输出目录映射
    deploy:
      resources:
        limits:
          memory: 4G  # 限制内存使用
          cpus: '2.0'  # 限制CPU使用
        reservations:
          memory: 1G
          cpus: '1.0'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - mineru-network

  # 可选：Nginx反向代理 (用于生产环境)
  nginx:
    image: nginx:alpine
    container_name: mineru-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mineru-m1
    networks:
      - mineru-network
    profiles:
      - production  # 只在生产模式下启动

volumes:
  mineru_models:
    driver: local
  mineru_cache:
    driver: local

networks:
  mineru-network:
    driver: bridge